[project]
name = "ocr-worker"
version = "0.1.0"
description = "OCR Service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "minio>=7.2.18",
    "pika>=1.3.2",
    "pytesseract>=0.3.13",
]
