spring:
  application:
    name: Batch-Processor

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

batch:
  input-dir: ${BATCH_INPUT_DIR:/tmp/access-logs/input}
  archive-dir: ${BATCH_ARCHIVE_DIR:/tmp/access-logs/input}

logging:
  level:
    root: INFO
    at.technikum.Batch_Processor: DEBUG
